
package student;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Kamere
 */
public class students extends javax.swing.JFrame {
public static ResultSet rs;
public static Statement stmt;
public static Connection conn;
public static int currow = 0;
    public students() throws SQLException {
        initComponents();
        doconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        student_no = new javax.swing.JTextField();
        reg_no = new javax.swing.JTextField();
        f_name = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        first_btn = new javax.swing.JButton();
        next_btn = new javax.swing.JButton();
        previous_btn = new javax.swing.JButton();
        last_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        update_record = new javax.swing.JButton();
        delete_record = new javax.swing.JButton();
        new_record = new javax.swing.JButton();
        save_record = new javax.swing.JButton();
        cancel_record = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID_NO");

        jLabel2.setText("GENDER");

        jLabel3.setText("FULL_NAME");

        jLabel4.setText("    EMAIL");

        jLabel6.setText("REG_NO");

        student_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_noActionPerformed(evt);
            }
        });

        reg_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_noActionPerformed(evt);
            }
        });

        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        jButton1.setText("This form show the student registered in the database and also allow to register other students");

        first_btn.setText("FIRST");
        first_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_btnActionPerformed(evt);
            }
        });

        next_btn.setText("NEXT");
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });

        previous_btn.setText("PREVIOUS");
        previous_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previous_btnActionPerformed(evt);
            }
        });

        last_btn.setText("LAST");
        last_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_btnActionPerformed(evt);
            }
        });

        update_record.setText("update record");
        update_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_recordActionPerformed(evt);
            }
        });

        delete_record.setText("delete record");
        delete_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_recordActionPerformed(evt);
            }
        });

        new_record.setText("new record");
        new_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_recordActionPerformed(evt);
            }
        });

        save_record.setText("save new record");
        save_record.setEnabled(false);
        save_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_recordActionPerformed(evt);
            }
        });

        cancel_record.setText("cancel new record");
        cancel_record.setEnabled(false);
        cancel_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_recordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(update_record, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(delete_record, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(new_record, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(save_record, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(cancel_record, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_record)
                    .addComponent(delete_record)
                    .addComponent(new_record))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_record)
                    .addComponent(cancel_record))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(first_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(next_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(student_no, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f_name, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(previous_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(last_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_btn)
                    .addComponent(next_btn)
                    .addComponent(previous_btn)
                    .addComponent(last_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void doconnect() throws SQLException{
String username="root";
String userpass="";
String dbname="jdbc:mysql://localhost/java_users";

 conn = DriverManager.getConnection(dbname,username,userpass);
       
  System.out.println("Connection successful");
  
    stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
  String SQL= "SELECT * FROM student_info";
  
  rs=stmt.executeQuery(SQL);
  System.out.println("Data object selected properly and stored in the rs");
 

  
  rs.next();
  int id_no = rs.getInt("student_id");
  String student_name= rs.getString("student_name");
  String student_regno=rs.getString("student_regno");
  String student_gender=rs.getString("student_gender");
  String student_email=rs.getString("student_email");
     
  //displaying the records
 String s_no = Integer.toString(id_no);
student_no.setText(s_no);
f_name.setText(student_name);
reg_no.setText(student_regno);
gender.setText(student_gender);
email.setText(student_email);
    }
    private void reg_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_noActionPerformed

    private void student_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_noActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void first_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_btnActionPerformed
try{
    
rs.first();
   int id_no = rs.getInt("student_id");
  String student_name= rs.getString("student_name");
  String student_regno=rs.getString("student_regno");
  String student_gender=rs.getString("student_gender");
  String student_email=rs.getString("student_email");
     
  //displaying the records
 String s_no = Integer.toString(id_no);
student_no.setText(s_no);
f_name.setText(student_name);
reg_no.setText(student_regno);
gender.setText(student_gender);
email.setText(student_email);
}
catch(SQLException err){
JOptionPane.showMessageDialog(students.this,err.getMessage());
}
    }//GEN-LAST:event_first_btnActionPerformed
    
    
   
    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed
       try{
           if(rs.next()){
             int id_no = rs.getInt("student_id");
  String student_name= rs.getString("student_name");
  String student_regno=rs.getString("student_regno");
  String student_gender=rs.getString("student_gender");
  String student_email=rs.getString("student_email");
     
  //displaying the records
 String s_no = Integer.toString(id_no);
student_no.setText(s_no);
f_name.setText(student_name);
reg_no.setText(student_regno);
gender.setText(student_gender);
email.setText(student_email);
           }else{
             rs.previous();
             JOptionPane.showMessageDialog(students.this,"end of file");
           }
       }
       catch(SQLException err){
       JOptionPane.showMessageDialog(students.this,"end of file");
   
       }
    }//GEN-LAST:event_next_btnActionPerformed

    private void previous_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previous_btnActionPerformed
      try{  if(rs.previous()){
            int id_no = rs.getInt("student_id");
  String student_name= rs.getString("student_name");
  String student_regno=rs.getString("student_regno");
  String student_gender=rs.getString("student_gender");
  String student_email=rs.getString("student_email");
     
  //displaying the records
 String s_no = Integer.toString(id_no);
student_no.setText(s_no);
f_name.setText(student_name);
reg_no.setText(student_regno);
gender.setText(student_gender);
email.setText(student_email);
          
          
      }else{
      rs.next();
      JOptionPane.showMessageDialog(students.this,"end of file");
      }
      }catch(SQLException err){
      JOptionPane.showMessageDialog(students.this,"end file");
      }
    }//GEN-LAST:event_previous_btnActionPerformed

    private void last_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_btnActionPerformed
try{  
    rs.last();
      int id_no = rs.getInt("student_id");
  String student_name= rs.getString("student_name");
  String student_regno=rs.getString("student_regno");
  String student_gender=rs.getString("student_gender");
  String student_email=rs.getString("student_email");
     
  //displaying the records
 String s_no = Integer.toString(id_no);
student_no.setText(s_no);
f_name.setText(student_name);
reg_no.setText(student_regno);
gender.setText(student_gender);
email.setText(student_email);
}   catch(SQLException err){
    JOptionPane.showMessageDialog(students.this, err.getMessage());
}  
    }//GEN-LAST:event_last_btnActionPerformed

    private void update_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_recordActionPerformed
String s_id = student_no.getText();
String s_names = f_name.getText();
String s_reg_no= reg_no.getText();
String s_gender = gender.getText();
String s_email = email.getText();
int new_id = Integer.parseInt(s_id);
try{
    rs.updateInt("student_id",new_id);
    rs.updateString("student_name", s_names);
     rs.updateString("student_regno", s_reg_no);
      rs.updateString("student_gender", s_gender);
    rs.updateString("student_email", s_email);
    rs.updateRow();
    JOptionPane.showMessageDialog(students.this,"record Updated");
    
}catch(SQLException err){
    JOptionPane.showMessageDialog(students.this, err.getMessage());
}

    }//GEN-LAST:event_update_recordActionPerformed

    private void new_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_recordActionPerformed
    try {
        currow = rs.getRow();
    } catch (SQLException ex) {
        Logger.getLogger(students.class.getName()).log(Level.SEVERE, null, ex);
    }
     student_no.setText("");
     f_name.setText("");
     reg_no.setText("");
     gender.setText("");
     email.setText("");
     first_btn.setEnabled(false);
     next_btn.setEnabled(false);
     previous_btn.setEnabled(false);
     last_btn.setEnabled(false);
     update_record.setEnabled(false);
     delete_record.setEnabled(false);
     save_record.setEnabled(true);
     cancel_record.setEnabled(true);
    }//GEN-LAST:event_new_recordActionPerformed

    private void save_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_recordActionPerformed
String s_id = student_no.getText();
String s_names = f_name.getText();
String s_reg_no= reg_no.getText();
String s_gender = gender.getText();
String s_email = email.getText();
int new_id = Integer.parseInt(s_id);

try{
    
    rs.moveToInsertRow();
    rs.updateString("student_name", s_names);
     rs.updateString("student_regno", s_reg_no);
      rs.updateString("student_gender", s_gender);
    rs.updateString("student_email", s_email);
    rs.insertRow();
    stmt.close();
    rs.close();
    
    stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
  String SQL= "SELECT * FROM student_info";
  
  rs=stmt.executeQuery(SQL);
  System.out.println("Data object selected properly and stored in the rs");
 

  
  rs.last();
  int id_nop = rs.getInt("student_id");
  String student_name= rs.getString("student_name");
  String student_regno=rs.getString("student_regno");
  String student_gender=rs.getString("student_gender");
  String student_email=rs.getString("student_email");
     
  //displaying the records
 String s_no = Integer.toString(id_nop);
student_no.setText(s_no);
f_name.setText(student_name);
reg_no.setText(student_regno);
gender.setText(student_gender);
email.setText(student_email);
    
    
    JOptionPane.showMessageDialog(students.this,"new record added");
    
}catch(SQLException err){
    JOptionPane.showMessageDialog(students.this, err.getMessage());
}
      
    }//GEN-LAST:event_save_recordActionPerformed

    private void cancel_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_recordActionPerformed

    try {
        rs.absolute(currow);
        first_btn.setEnabled(true);
        next_btn.setEnabled(true);
        previous_btn.setEnabled(true);
        last_btn.setEnabled(true);
        update_record.setEnabled(true);
        delete_record.setEnabled(true);
        save_record.setEnabled(false);
        cancel_record.setEnabled(false); 
        
        int id = rs.getInt("student_id");
        String st_id = Integer.toString(id);
        student_no.setText(st_id);
        f_name.setText(rs.getString("student_name"));
        reg_no.setText(rs.getString("student_regno"));
        gender.setText(rs.getString("student_gender"));
        email.setText(rs.getString("student_email"));


    } catch (SQLException ex) {
        Logger.getLogger(students.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_cancel_recordActionPerformed

    private void delete_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_recordActionPerformed
    try {
        if(rs.next()){
        rs.deleteRow();
        stmt.close();
        rs.close();
         
    stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
  String SQL= "SELECT * FROM student_info";
  
  rs=stmt.executeQuery(SQL);
  System.out.println("Data object selected properly and stored in the rs");
 

  
  rs.next();
  int id_no = rs.getInt("student_id");
  String student_name= rs.getString("student_name");
  String student_regno=rs.getString("student_regno");
  String student_gender=rs.getString("student_gender");
  String student_email=rs.getString("student_email");
     
  //displaying the records
 String s_no = Integer.toString(id_no);
student_no.setText(s_no);
f_name.setText(student_name);
reg_no.setText(student_regno);
gender.setText(student_gender);
email.setText(student_email);
        }else{
            JOptionPane.showMessageDialog(students.this,"All record deleted");
        }
    } catch (SQLException ex) {
        Logger.getLogger(students.class.getName()).log(Level.SEVERE, null, ex);
    }
      
    }//GEN-LAST:event_delete_recordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new students().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(students.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton cancel_record;
    private javax.swing.JButton delete_record;
    public static javax.swing.JTextField email;
    public static javax.swing.JTextField f_name;
    public static javax.swing.JButton first_btn;
    public static javax.swing.JTextField gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JButton last_btn;
    public static javax.swing.JButton new_record;
    public static javax.swing.JButton next_btn;
    public static javax.swing.JButton previous_btn;
    public static javax.swing.JTextField reg_no;
    public static javax.swing.JButton save_record;
    public static javax.swing.JTextField student_no;
    private javax.swing.JButton update_record;
    // End of variables declaration//GEN-END:variables
}
